name: Release

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x
    - name: Cross build
      run: make cross
    - name: Create Release
      run: gh release create "$GITHUB_REF_NAME" --title "Release $GITHUB_REF_NAME" --generate-notes goxz/*
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
